### ISSUE TITLE
docker build issue

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#11]
i keep getting this error. im on unraid 6.10.03
```
=> ERROR [ 6/11] RUN groupadd --force -g  sail                                                                                                                            2.4s
------                                                                                                                                                                          
 > [ 6/11] RUN groupadd --force -g  sail:
#0 1.944 groupadd: invalid group ID 'sail'
------
failed to solve: executor failed running [/bin/sh -c groupadd --force -g $WWWGROUP sail]: exit code: 3
```

**Comment by newelement** [comment]
I'm not sure. Sail is a first party package of Laravel, the framework this is built on. You might have to check with the Laravel group

**Comment by binarygeek119** [comment]
ok i got it to build now using `docker-compose --env-file .envstart up`
and inside the file i have.

```
WWWGROUP=1000
WWWUSER=1000
DB_DATABASE=movieposter
DB_PASSWORD=movieposter
DB_USERNAME=movieposter
VITE_PORT=5173
FORWARD_DB_PORT=3307
```

but i had to go in and add the mysql database myself along with the other db commands.
after which i got it to run i can get into settings add posters etc. but i cant get it to display them. 
in devtools i have this error now

```
GET http://192.168.0.134:8084/socket.io/?EIO=4&transport=polling&t=OCehf2t 404 (Not Found)
create @ app.62969775.js:2
Pn @ app.62969775.js:2
request @ app.62969775.js:2
doPoll @ app.62969775.js:2
poll @ app.62969775.js:2
doOpen @ app.62969775.js:2
open @ app.62969775.js:2
open @ app.62969775.js:2
qn @ app.62969775.js:2
open @ app.62969775.js:2
(anonymous) @ app.62969775.js:2
setTimeout (async)
reconnect @ app.62969775.js:2
maybeReconnectOnOpen @ app.62969775.js:2
(anonymous) @ app.62969775.js:2
pt.emit @ app.62969775.js:2
onError @ app.62969775.js:2
pt.emit @ app.62969775.js:2
onError @ app.62969775.js:2
(anonymous) @ app.62969775.js:2
pt.emit @ app.62969775.js:2
onError @ app.62969775.js:2
(anonymous) @ app.62969775.js:2
setTimeout (async)
n.onreadystatechange @ app.62969775.js:2

```

**Comment by newelement** [comment]
The first line `GET http://192.168.0.134:8084/socket.io/?EIO=4&transport=polling&t=OCehf2t 404 (Not Found)` means the websocket server is not running.

In the project root are you able to run:

`./vendor/bin/sail up`

**Comment by binarygeek119** [comment]
that ended up with this screen ![image](https://user-images.githubusercontent.com/72405030/189518463-54bb91f3-7da5-449e-96ef-9513ae6d1a95.png)

[laravel.log](https://github.com/newelement/digital-movie-poster/files/9542063/laravel.log)

**Comment by newelement** [comment]
That is a permission issue. Without knowing your groups and users, typically for Laravel we have to set these permissions in the. project root:
```
chgrp -R www-data storage bootstrap/cache
chmod -R ug+rwx storage bootstrap/cache
```

**Comment by binarygeek119** [comment]
i ran the commands for permissions and it went back to say 'GET http://192.168.0.134:8084/socket.io/?EIO=4&transport=polling&t=OCehf2t 404 (Not Found)'
maybe i set it up wrong. can you give some instructions on how to run this as docker.
i come from unraid and just use there app store to fill in template for each app.
https://forums.unraid.net/topic/38582-plug-in-community-applications/

**Comment by binarygeek119** [comment]
i see this error in the docker compose output
`/usr/local/bin/start-container: line 18: cd: /var/www/html/wsserver: No such file or directory`

**Comment by binarygeek119** [comment]
i got it to build and run
