### ISSUE TITLE
how to update

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#13]
i was wanting to know about update dmp do i just click it or are there steps for updating before clicking?

**Comment by newelement** [comment]
There is an update script. Under the settings page there is a link at the bottom next to the Save Settings button titled Update DMP. The functionality has only been tested on a Raspberry Pi. It will require git and npm to be installed.

The more I look at the location of that link, I don't think it's in a very good location.

**Comment by binarygeek119** [comment]
ok thank you.
