### ISSUE TITLE
emby missing

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#14]
i think you need to add emby as a separate poster source. 
something must be different to jellyfin. 
i cant get now playing to sync or show up under emby.
i also cant get it to pull posters from emby to sync the poster with what i have.

**Comment by newelement** [comment]
Ah ok, I thought. Jellyfin kinda took over Emby. Sorry if I'm not correct.

**Comment by binarygeek119** [comment]
i will help out anyway you need for testing

**Comment by newelement** [comment]
@binarygeek119 My apologies, but I'm going to close this one. I'm not planning on supporting emby as a first party media source. There will be a plugin structure soon for others to add media sources soon.
