### ISSUE TITLE
some request for features

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#16]
more customizable logos
i like to be able to show my surround sound setup in my case a 5.1
i was thinking that you can check what dolby the user has for the logo then add the speaker setup next to it

- Dolby Digital.
- Dolby Digital EX.
- Dolby Digital Surround EX.
- Dolby Digital Live.
- Dolby Digital Plus.
- Dolby AC-4.
- Dolby TrueHD.

speaker setups

- 2.0
- 2.1
- 3.0
- 3.1
- 5.0
- 5.1
- 7.0
- 7.1
- 5.2
- 7.2
also i have a 3d projector and would like to display that.

- Active-shutter 3D
- Passive 3D
- Dolby 3D
- RealD
- IMAX digital
- Anaglyph 3D
also being able to show what movies are available in 3d in plex/jellyfin/emby/kodi or just in general

rating limits being able to limite what is shown so if pg-13 is the max rating then no rated r with be display

tv show could also be nice for some people to display.

and then one i really like for sure 
ads
being able to set up custom ads like ones i have made inwhick you can include if you like
  https://github.com/binarygeek119/posterr-custom-posters
i can also make more if you wish

also sorry for bombarding you. just really excited for this project i came here from posterr.
have you thought about posting your app to docker https://hub.docker.com/ it could get more looks.
also the plex/emby/jellyfin/kodi reddit's
and have you considered setting up a donation link. i would sign up on patreon to keep this going.

**Comment by newelement** [comment]
I like these. I'm not 100% comfortable heavily promoting DMP yet. I'm getting there.

**Comment by newelement** [comment]
@binarygeek119 I'm going to add the ability to display the speaker config. 5.1, 7.2.4 etc... I'm trying to think of the best place to display that. Screen real estate is getting thin. I'm not using the top right area next to the Coming Soon/Now Playing. I'm not sure if I like that or not though.  What are your thought?

**Comment by binarygeek119** [comment]
I think maybe have a limit to the number of items to be on display. Or have them fade in and out switching between them. Or have the scroll from left to right then right to left. I think I like the scrolling items the best. That way you can have as much as you want to be displayed.

So I think you get X limit of slots to add to display or you can cycle though them with some animations.  A SLOW SLIDE WOULD BE NEat one by one sliding across the screen then bump off when too full.

What are your thoughts?

**Comment by newelement** [comment]
Yeah, I need to think about it for a bit

**Comment by binarygeek119** [comment]
new idea be able to set dates for show themed posters
10/01/22 - 10/31/22 would show halloween
12/01/22 - 12/31/22 would show x-mas movies
i think it best to just use month/day
and a way to use it would be by release date and/or tag 
tags could be use from tmdb Keywords
here is Hocus Pocus (1993)'s keywords as a example
![image](https://user-images.githubusercontent.com/72405030/195625923-f13a1d57-915c-4e00-a65c-de92aeca04af.png)

**Comment by newelement** [comment]
I am adding timed and tagged poster views to the to do list.

**Comment by newelement** [comment]
I have added schedule and tagging. I'm going to close this. Please submit new features going forward in its own issue request. Thanks!!!!!
