### ISSUE TITLE
Native Media Player Plug-in

### ISSUE THREAD

**Issue by schwos** [newelement/digital-movie-poster#25]
Appreciate the effort put into the development of this. I'm currently on mission to step out of polling updates from plex, jellyfin etc as that's only one source. What id think be nice is plug-in interface to add the media player to poll for example Roku, Nvidia Shield, and drum roll Apple TV. 

Then the post can be impacted by app streaming, put associate poster up and at bottom state App used. I know the data is available on Roku, and nvidia shield. Apple TV it's possible just need to test on tvos 16.

**Comment by newelement** [comment]
I have been thinking about this. I would have to come up with a standard way to query or listen for events for these devices. Even getting what's currently playing from Plex, Kodi and Jellyfin have all been entirely different. The only thing I could probably do is offer a way to register a plugin then offer the method to tell DMP that something is playing somewhere.

**Comment by schwos** [comment]
Agree, I see in the folder services that you have the code for kodi, plex, and jellyfin. I will install the system and play but recommend a way to prioritize the services and we just add apple, roku, and nvidiA. Ill take a stab at one of them and we can query at min. 

with apple we can leverage node-appletv. we would just need to expand the services to be able to pair with the remote device on network and get paid key. should be able to query the device at a set interval. 

there are plenty of roku api adaptions out there we could leverage and i believe nvidia shield is similar api set but haven't dug into it.

**Comment by newelement** [comment]
The app\Services items are mostly for syncing movie/tv data. The websocket and polling for now playing is in the resources/js/store/posters.js file

**Comment by newelement** [comment]
I've added an API endpoint for `now-playing` events. I need to add new documentation for all this which I have not done yet.

**Comment by newelement** [comment]
I have added some API docs to the README.

**Comment by schwos** [comment]
Thanks I am reviewing and determining integration.. I am going to start with a more open platform Roku..

**Comment by newelement** [comment]
I am going to make a formal plugin structure soon. It will be a composer/laravel package.

**Comment by newelement** [comment]
Closing this now as there is a way to create a plugin. Please submit an issue for questions.
