### ISSUE TITLE
error Connection refused

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#29]
i rebuild the docker image and now i cant get posters to show up. it doesnt load the webp image in the root url or the /posters just shows a empty space.
[laravel-2022-10-14.log](https://github.com/newelement/digital-movie-poster/files/9787564/laravel-2022-10-14.log)

**Comment by newelement** [comment]
Thats the new redis service. I did test it locally on docker. I'll look into it soon and see if there is something I missed.
