### ISSUE TITLE
kodi's poster pull doesn't work ether

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#33]
kodi version Kodi v19.4 (Matrix) ive tryied windows app and installer version aswell as a vm with unraid LibreELEC all do the some thing all setup the same
after sync posters with kodi setup 
![image](https://user-images.githubusercontent.com/72405030/199161826-0f6ff8c1-bd35-4794-aea6-33aaf1f0635c.png)

devtools output
![image](https://user-images.githubusercontent.com/72405030/199161874-74b90c48-b7e9-4778-8d2f-335d9e40059a.png)

kodi settings 
![image](https://user-images.githubusercontent.com/72405030/199161929-cce5e84a-d720-4210-bf67-5ec6c0fe5ca2.png)

kodi webport
![image](https://user-images.githubusercontent.com/72405030/199161989-a19dd7ca-95d8-4ba6-912b-5899d459c3b8.png)

**Comment by newelement** [comment]
I am currently re-doing all the posters sources and creating a plugin structure. All the source connections will change soon.
