### ISSUE TITLE
kodi plugin wont install

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#35]
the kodi plugin wont install. i click it and it says downloading then nothing else happens

**Comment by binarygeek119** [comment]
[laravel-2022-11-10.log](https://github.com/newelement/digital-movie-poster/files/9985238/laravel-2022-11-10.log)

**Comment by newelement** [comment]
Those errors are from Predis (PHP Redis). Im not sure why that is causing issues with the plugin.

**Comment by newelement** [comment]
I may have you try some permission changes. I'll post when I get a chance.
