### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by opsteel** [newelement/digital-movie-poster#4]
I am trying to set this up and I am running in to an issue with the php artisan migrate command. Please see the error below. Thanks for your help and I am looking forward to trying your software.

pi@poster:/var/www/html/digital-movie-poster $ php artisan migrate

   UnexpectedValueException

  The stream or file "/var/www/html/digital-movie-poster/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: Permission denied

  at vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142▕             restore_error_handler();
    143▕             if (!is_resource($stream)) {
    144▕                 $this->stream = null;
    145▕
  ➜ 146▕                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147▕             }
    148▕             stream_set_chunk_size($stream, $this->streamChunkSize);
    149▕             $this->stream = $stream;
    150▕         }

      +9 vendor frames
  10  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException(Object(UnexpectedValueException))

**Comment by opsteel** [comment]
Forgot to mention, I attempted to change ownership of the directory and that did not help.

sudo chown -R www-data:www-data /var/www/html

**Comment by newelement** [comment]
Closing
