### ISSUE TITLE
backup settings and database

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#42]
it would be nice if we could do a one click and get a backup of all settings. if the need to reflash is needed.

then a upload setting to restore settings and posters.

it would then load the missing poster in background.

**Comment by newelement** [comment]
Oh this is already high up on my todo list. I'm tired of resetting my data locally.

**Comment by newelement** [comment]
I have added the ability to do backups and restores. The catch is it requires mysqldump command to be present.
