### ISSUE TITLE
theater ads

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#44]
be nice to use theater ads
i like to be able to show a ads every 10 posters.
i think the number needs to be user configurable.

just a few examples of ones i  made 
https://github.com/binarygeek119/open-custom-posters

**Comment by newelement** [comment]
Would the ad be a complete overlay of the interface? Like cover up the top header, poster and bottom footer areas?

**Comment by binarygeek119** [comment]
i was thing just show the add inside of interface just like movie posters. no need to cover it up in my mind.

**Comment by newelement** [comment]
I have some good stuff coming for this.

**Comment by newelement** [comment]
I have added an Overlays section. These can be set to show at poster intervals. These can either be images or mp4 videos.
