### ISSUE TITLE
GET POSTER.webp 404 (Not Found)

### ISSUE THREAD

**Issue by logseven** [newelement/digital-movie-poster#46]
Hello,

Thank you very much for your software but I have a small problem, all the images are not found, I tried Plex / TMDB and upload myself but each time it does not find the poster.

apocalypse-now.webp:1          GET http://raspberrypi.local/storage/posters/apocalypse-now.webp 404 (Not Found)

I have nothing in the logs

Thanks to you for your help,

**Comment by logseven** [comment]
when I try to delete a movie it marks me that 

```
POST http://raspberrypi.local/api/posters/2 500 (Internal Server Error)
(anonymous) @ app.92c5bd6d.js:2
Sp @ app.92c5bd6d.js:2
Op @ app.92c5bd6d.js:2
request @ app.92c5bd6d.js:2
(anonymous) @ app.92c5bd6d.js:2
(anonymous) @ app.92c5bd6d.js:1
deletePoster @ app.92c5bd6d.js:29
mr @ app.92c5bd6d.js:5
Rn @ app.92c5bd6d.js:5
uv @ app.92c5bd6d.js:5
deletePoster @ app.92c5bd6d.js:20
e.showDelete.d.onClick.t.<computed>.t.<computed> @ app.92c5bd6d.js:20
mr @ app.92c5bd6d.js:5
Rn @ app.92c5bd6d.js:5
n @ app.92c5bd6d.js:5
app.92c5bd6d.js:29 Request failed with status code 500
```

**Comment by newelement** [comment]
Sounds like a permission issue with the ability to save the images. Did you use the install script or install/setup your own web server etc ?
