### ISSUE TITLE
new emby sdk

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#49]
emby just updated there sdk
here the video
https://www.youtube.com/watch?v=kFY15NhxR9M
here's the sdk
https://dev.emby.media/

**Comment by newelement** [comment]
Thanks for the heads up. They still require use auth to access libraries. Same for Jellyfin except they added it but have yet to tag it for a release and may never do so. I was trying to avoid saving any usernames and passwords in the database. I can encrypt them, but was hoping for a better solution on Emby/Jellyfin's end. I may change my mind soon.
