### ISSUE TITLE
emby/jellyfin support

### ISSUE THREAD

**Issue by binarygeek119** [newelement/digital-movie-poster#5]
i like to have emby to use as a media server for this app
emby/jellyfin are built for the same source when emby went closed source jellyfin was born.
if you add support for one the other be easy to adept to.
jellyfin is free 100%
emby is like plex

emby api
https://github.com/MediaBrowser/Emby/wiki

jellyfin api
https://jellyfin.org/docs/plugin-api/index.html
https://api.jellyfin.org/
http://your-jellyfin-server:8096/api-docs/swagger/index.html

**Comment by newelement** [comment]
Sorry for the late reply. I'm finally getting back to this project. Thanks for the suggestions. I'll see what I can do.
